name: harupass

packages:
  - packages/*

sdkPath: auto

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: dart analyze .
    exec:
      concurrency: 5
    packageFilters:
      flutter: true

  test:
    run: flutter test
    exec:
      concurrency: 5
    packageFilters:
      dirExists: test

  clean:
    run: flutter clean
    exec:
      concurrency: 5

  build:android:
    run: flutter build apk --release
    packageFilters:
      scope: harupass
